package com.example.demo.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;

import java.util.List;
import java.util.Set;
import java.util.UUID;

@Data
@DynamoDBTable(tableName = "product")
@DynamoDbBean
public class Product {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id = UUID.randomUUID().toString();
  @DynamoDBAttribute
  private String sku;
  @DynamoDBAttribute
  private String supplierSku;
  @DynamoDBAttribute
  private String supplierCode;
  @DynamoDBAttribute
  private String productType;
  @DynamoDBAttribute
  private List<Product> gifts;
}